/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Provider } from '@ethersproject/providers'
import { Contract, Signer } from 'ethers'

import { abi } from '@/abi/misc/UiPoolDataProvider.sol/UiPoolDataProvider.json'

export default (address: string, signerOrProvider: Signer | Provider): Contract => {
    return new Contract(address, abi, signerOrProvider)
}
